changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - feature
      filters:
        include:
          - "^feat:"

    - title: 🐛 Bug Fixes
      labels:
        - bug
      filters:
        include:
          - "^fix:"

    - title: 🛠️ Maintenance & Other Changes
      labels:
        - maintenance
        - "*"
      filters:
        include:
          - "^chore:"

    - title: 🔄 Other Changes
      labels:
        - "*"
