name-template: '🚀 Release v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🆕 Features'
    labels: ['feature', 'enhancement']
  - title: '🐞 Bug Fixes'
    labels: ['bug', 'fix']
  - title: '🔄 Changes'
    labels: ['refactor', 'change']
  - title: '🛠 Technical Updates'
    labels: ['chore', 'internal']
change-template: '- $TITLE [#$NUMBER](https://github.com/${{ github.repository }}/commit/$COMMIT) by @$AUTHOR'
template: |
  # 🚀 Release v$NEXT_PATCH_VERSION

  ## 📌 Summary
  $RELEASE_NOTES

  ## 🔄 Changes
  $CHANGES

  ## 🆕 Features
  $FEATURES

  ## 🐞 Bug Fixes
  $BUG_FIXES

  ## 🛠 Technical Updates
  $OTHER

  ## 📁 Downloads
  - [Windows Executable](https://github.com/${{ github.repository }}/releases/download/v$NEXT_PATCH_VERSION/your-app.exe)
  - SHA256 Checksum: `TODO: Add checksum calculation`
  - [Source Code](https://github.com/${{ github.repository }}/releases/tag/v$NEXT_PATCH_VERSION)

  ## 🙌 Contributors
  $CONTRIBUTORS
