name: 🚀 Auto Release Notes

on:
  push:
    branches:
      - main  # Runs on every push to master
  workflow_dispatch: # Allows manual trigger from GitHub UI
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight (optional)

permissions:
  contents: write  # Required to update release notes

jobs:
  update_release_draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v6
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
